"""baseline schema

Revision ID: d80229e5a45c
Revises: 
Create Date: 2026-06-24 16:41:03.520767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80229e5a45c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halt_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('n_rounds', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_catalog',
    sa.Column('tactic', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('first_run_id', sa.String(), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('total_dollars', sa.Float(), nullable=False),
    sa.Column('dollars_samples', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tactic', 'target_type')
    )
    op.create_table('blue_rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('features_added', sa.JSON(), nullable=False),
    sa.Column('detection_before', sa.Float(), nullable=False),
    sa.Column('detection_after', sa.Float(), nullable=False),
    sa.Column('recovered', sa.Float(), nullable=False),
    sa.Column('n_holdout', sa.Integer(), nullable=False),
    sa.Column('proposer_rationale', sa.String(), nullable=False),
    sa.Column('new_model_ref', sa.String(), nullable=True),
    sa.Column('iteration_trail', sa.JSON(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('raw_response', sa.String(), nullable=True),
    sa.Column('parsed_output', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('dollars', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specs',
    sa.Column('spec_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('spec_id')
    )
    op.create_table('white_box_metrics',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('white_box_run_id', sa.String(), nullable=True),
    sa.Column('black_box_catch_rate', sa.Float(), nullable=True),
    sa.Column('white_box_catch_rate', sa.Float(), nullable=True),
    sa.Column('white_box_gap', sa.Float(), nullable=True),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('txn_index', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('true_label', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('txn_slice', sa.String(), nullable=False),
    sa.Column('parent_txn_id', sa.String(), nullable=True),
    sa.Column('detector_score', sa.Float(), nullable=False),
    sa.Column('caught', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('parent_txn_id', sa.String(), nullable=False),
    sa.Column('mutation_json', sa.JSON(), nullable=False),
    sa.Column('pre_score', sa.Float(), nullable=False),
    sa.Column('post_score', sa.Float(), nullable=False),
    sa.Column('evaded', sa.Boolean(), nullable=False),
    sa.Column('true_label_preserved', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('aggregate_pass', sa.Boolean(), nullable=False),
    sa.Column('fail_weight', sa.Float(), nullable=False),
    sa.Column('pass_weight', sa.Float(), nullable=False),
    sa.Column('audit_trace_json', sa.JSON(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oracle_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('verdict_id', sa.String(), nullable=False),
    sa.Column('oracle_kind', sa.String(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oracle_votes')
    op.drop_table('verdicts')
    op.drop_table('attacks')
    op.drop_table('transactions')
    op.drop_table('white_box_metrics')
    op.drop_table('specs')
    op.drop_table('rounds')
    op.drop_table('llm_calls')
    op.drop_table('blue_rounds')
    op.drop_table('strategy_catalog')
    op.drop_table('runs')
    op.drop_table('halt_state')
    # ### end Alembic commands ###
