"""initial schema

Revision ID: 0d53d7aa0e3b
Revises: 
Create Date: 2026-06-23 19:00:15.478133
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d53d7aa0e3b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_probes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('subcomponent', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_self_test_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_ref', sa.String(length=256), nullable=False),
    sa.Column('spec_title', sa.String(length=512), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_max_attempts', sa.Integer(), nullable=False),
    sa.Column('budget_max_dollars', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tactic', sa.String(length=256), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('white_box', sa.Boolean(), nullable=False),
    sa.Column('hybrid', sa.Boolean(), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('modal_job_id', sa.String(length=128), nullable=False),
    sa.Column('env_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('network_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('attack_id', sa.String(length=64), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('tally', sa.Float(), nullable=False),
    sa.Column('votes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_table('sandbox_jobs')
    op.drop_table('llm_calls')
    op.drop_table('attacks')
    op.drop_table('runs')
    op.drop_table('health_probes')
    # ### end Alembic commands ###
