"""per-oracle detail tables

Revision ID: 36b9359a0eec
Revises: bf7fbd9b36a8
Create Date: 2026-06-24 03:44:47.673809
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b9359a0eec'
down_revision: str | None = 'bf7fbd9b36a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('differential_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('verdict_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuzz_findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('verdict_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('counterexample', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge_votes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('verdict_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judge_votes')
    op.drop_table('fuzz_findings')
    op.drop_table('differential_runs')
    # ### end Alembic commands ###
