"""blue loop tables

Revision ID: bf7fbd9b36a8
Revises: e40347a6be4a
Create Date: 2026-06-24 00:26:59.794140
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf7fbd9b36a8'
down_revision: str | None = 'e40347a6be4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blue_patches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['blue_patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_agent_config_version')
    )
    op.create_table('holdout_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patch_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('holdout_size', sa.Integer(), nullable=False),
    sa.Column('detection_before', sa.Float(), nullable=False),
    sa.Column('detection_after', sa.Float(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['blue_patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('artifact_ref', sa.String(length=256), nullable=False),
    sa.Column('patch_id', sa.String(length=64), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['blue_patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'version', name='uq_model_version_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_versions')
    op.drop_table('holdout_runs')
    op.drop_table('agent_configs')
    op.drop_table('blue_patches')
    # ### end Alembic commands ###
