"""strategy_catalog table

Revision ID: e40347a6be4a
Revises: 1f71e3aae85e
Create Date: 2026-06-23 23:05:46.813508
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e40347a6be4a'
down_revision: str | None = '1f71e3aae85e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_catalog',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tactic', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('first_run_id', sa.String(length=64), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('total_dollars', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=False),
    sa.Column('discovery_audit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tactic', 'target_type', name='uq_strategy_tactic_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_catalog')
    # ### end Alembic commands ###
