"""halt state table

Revision ID: ec4dc1906055
Revises: 36b9359a0eec
Create Date: 2026-06-24 04:13:54.611957
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4dc1906055'
down_revision: str | None = '36b9359a0eec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halt_state',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('halt_state')
    # ### end Alembic commands ###
