"""core schema: runs specs attacks verdicts llm_calls sandbox_jobs health_probes

Revision ID: 402ffe03d4a7
Revises: 
Create Date: 2026-06-22 22:15:24.663007
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '402ffe03d4a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_probes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('subcomponent', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('budget_rounds', sa.Integer(), nullable=False),
    sa.Column('budget_dollars', sa.Float(), nullable=False),
    sa.Column('dollars_spent', sa.Float(), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('white_box_recall', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('tactic', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('white_box', sa.Boolean(), nullable=False),
    sa.Column('hybrid', sa.Boolean(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6, asdecimal=False), nullable=False),
    sa.Column('seed', sa.String(length=64), nullable=False),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_run_id'), 'attacks', ['run_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_output', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('dollars', sa.Float(), nullable=False),
    sa.Column('seed', sa.String(length=64), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_run_id'), 'llm_calls', ['run_id'], unique=False)
    op.create_table('sandbox_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('job_ref', sa.String(length=120), nullable=False),
    sa.Column('env_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('network_rules', sa.String(length=120), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('seed', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_jobs_run_id'), 'sandbox_jobs', ['run_id'], unique=False)
    op.create_table('specs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('holdout_generator_kind', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specs_run_id'), 'specs', ['run_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('attack_id', sa.String(length=64), nullable=False),
    sa.Column('producer_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('votes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tally', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('dollars_spent', sa.Numeric(precision=12, scale=6, asdecimal=False), nullable=False),
    sa.Column('seed', sa.String(length=64), nullable=False),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_action_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_attack_id'), 'verdicts', ['attack_id'], unique=False)
    op.create_index(op.f('ix_verdicts_run_id'), 'verdicts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_run_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_attack_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_specs_run_id'), table_name='specs')
    op.drop_table('specs')
    op.drop_index(op.f('ix_sandbox_jobs_run_id'), table_name='sandbox_jobs')
    op.drop_table('sandbox_jobs')
    op.drop_index(op.f('ix_llm_calls_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_attacks_run_id'), table_name='attacks')
    op.drop_table('attacks')
    op.drop_table('runs')
    op.drop_table('health_probes')
    # ### end Alembic commands ###
