"""run.agent_config_id (cr-e2 BYO)

Revision ID: 87b8a2f18358
Revises: f6d47e840d9c
Create Date: 2026-06-24 16:24:20.225128
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87b8a2f18358'
down_revision: str | None = 'f6d47e840d9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('agent_config_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'agent_config_id')
    # ### end Alembic commands ###
