"""agent_configs + spec versioning (cr-a2)

Revision ID: b15af09d6523
Revises: 402ffe03d4a7
Create Date: 2026-06-24 15:01:02.894382
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b15af09d6523'
down_revision: str | None = '402ffe03d4a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('parent_config_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_name'), 'agent_configs', ['name'], unique=False)
    op.create_index(op.f('ix_agent_configs_run_id'), 'agent_configs', ['run_id'], unique=False)
    op.add_column('specs', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # server_default backfills any pre-existing spec rows; the ORM sets these going forward.
    op.add_column('specs', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('specs', sa.Column('compiler', sa.String(length=40), nullable=False, server_default='deterministic'))
    op.add_column('specs', sa.Column('source_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('specs', sa.Column('parent_spec_id', sa.String(length=64), nullable=True))
    op.alter_column('specs', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specs', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('specs', 'parent_spec_id')
    op.drop_column('specs', 'source_text')
    op.drop_column('specs', 'compiler')
    op.drop_column('specs', 'version')
    op.drop_column('specs', 'created_at')
    op.drop_index(op.f('ix_agent_configs_run_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_name'), table_name='agent_configs')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
