"""runs.target_http (cr-ui4 BYO http)

Revision ID: e98a2f6a4a67
Revises: 87b8a2f18358
Create Date: 2026-06-25 17:52:46.361564
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e98a2f6a4a67'
down_revision: str | None = '87b8a2f18358'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('target_http', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'target_http')
    # ### end Alembic commands ###
