"""coevolution_rounds (cr-d3)

Revision ID: f6d47e840d9c
Revises: b15af09d6523
Create Date: 2026-06-24 16:07:57.402703
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f6d47e840d9c'
down_revision: str | None = 'b15af09d6523'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coevolution_rounds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('n_attacks', sa.Integer(), nullable=False),
    sa.Column('n_caught', sa.Integer(), nullable=False),
    sa.Column('asr', sa.Float(), nullable=False),
    sa.Column('detection', sa.Float(), nullable=False),
    sa.Column('patch_id', sa.String(length=64), nullable=True),
    sa.Column('safe_before', sa.Float(), nullable=True),
    sa.Column('safe_after', sa.Float(), nullable=True),
    sa.Column('audit_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coevolution_rounds_run_id'), 'coevolution_rounds', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coevolution_rounds_run_id'), table_name='coevolution_rounds')
    op.drop_table('coevolution_rounds')
    # ### end Alembic commands ###
