"""Differential oracle: a second implementation from a different model family.

For code, the producer's implementation (Sonnet) is compared against a second
implementation generated by Haiku, a different family. Both run on the same
inputs in the sealed sandbox and their outputs are compared. A disagreement is
flagged without declaring either side correct: the platform never trusts a
single side as ground truth (ARCHITECTURE.md decision table). The fraud variant
(LightGBM versus IsolationForest) is a follow-on; this slice ships the code
differential.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from typing import Any

from shared.llm import LlmClient, LlmModel
from shared.sandbox import DockerSandbox, SandboxResult
from shared.source import extract_python_source, is_valid_python
from shared.types import (
    OracleVote,
    ProbeResult,
    ProbeStatus,
    SealedSpec,
    TargetOutput,
    VerdictDecision,
)

_DIFF_MARKER = "__CRUCIBLE_DIFF__"


def build_diff_harness(source_a: str, source_b: str, inputs: list[str]) -> str:
    """A sandbox script that runs two implementations on the same inputs.

    Each implementation is exec'd into its own namespace (so both may define a
    function of the same name), every input expression is evaluated in both, and
    a mismatch (including one side raising while the other does not) is recorded.
    The result is printed as one marker-prefixed JSON line.
    """
    return (
        "import json\n"
        "_A: dict = {}\n_B: dict = {}\n"
        f"exec({source_a!r}, _A)\n"
        f"exec({source_b!r}, _B)\n"
        f"_inputs = {inputs!r}\n"
        "_m = []\n"
        "for _e in _inputs:\n"
        "    try:\n        _ra = eval(_e, dict(_A))\n"
        "    except Exception as _ex:\n        _ra = ('ERR', type(_ex).__name__)\n"
        "    try:\n        _rb = eval(_e, dict(_B))\n"
        "    except Exception as _ex:\n        _rb = ('ERR', type(_ex).__name__)\n"
        "    if _ra != _rb:\n        _m.append({'input': _e, 'a': str(_ra), 'b': str(_rb)})\n"
        f"print({_DIFF_MARKER!r} + json.dumps({{'total': len(_inputs), 'mismatches': _m}}))\n"
    )


def parse_diff(result: SandboxResult) -> dict[str, Any] | None:
    """Pull the differential report out of the sandbox stdout, or None on error."""
    for line in result.stdout.splitlines():
        if line.startswith(_DIFF_MARKER):
            parsed: dict[str, Any] = json.loads(line[len(_DIFF_MARKER) :])
            return parsed
    return None


@dataclass(frozen=True, slots=True)
class DifferentialOracle:
    """Cross-family agreement check for code producers."""

    llm: LlmClient
    sandbox: DockerSandbox
    name: str = "differential"
    weight: float = 1.0
    second_model: LlmModel = LlmModel.HAIKU
    input_model: LlmModel = LlmModel.SONNET
    min_inputs: int = 3

    @property
    def protocol_description(self) -> str:
        return (
            "Generates a second implementation from a different model family (Haiku) plus "
            "concrete comparison inputs, runs both against your output in the sealed "
            "sandbox, and flags disagreement without trusting either side as ground truth."
        )

    async def verify(
        self,
        spec: SealedSpec,
        attack_input: dict[str, Any],
        output: TargetOutput,
    ) -> OracleVote:
        obligation_id = spec.obligations[0].id if spec.obligations else None
        if not isinstance(output.output, str):
            return self._vote(
                VerdictDecision.UNAVAILABLE,
                "differential code mode needs source output; the fraud variant "
                "(LightGBM versus IsolationForest) is a follow-on",
                obligation_id,
            )

        second = await self._second_implementation(spec)
        if not is_valid_python(second):
            return self._vote(
                VerdictDecision.UNAVAILABLE,
                "the second-family implementation did not parse; cannot compare",
                obligation_id,
            )
        inputs = await self._comparison_inputs(spec)
        if len(inputs) < self.min_inputs:
            return self._vote(
                VerdictDecision.UNAVAILABLE,
                f"only {len(inputs)} comparison inputs; need at least {self.min_inputs}",
                obligation_id,
            )

        harness = build_diff_harness(output.output, second, inputs)
        report = parse_diff(await self.sandbox.run_python(harness))
        if report is None:
            return self._vote(
                VerdictDecision.UNAVAILABLE,
                "differential harness produced no report, inconclusive",
                obligation_id,
            )

        total = report["total"]
        mismatches = report["mismatches"]
        if mismatches:
            first = mismatches[0]
            return self._vote(
                VerdictDecision.FAIL,
                f"the two model families disagree on {len(mismatches)} of {total} inputs, "
                f"neither trusted as ground truth (first: {first['input']} gave "
                f"{first['a']} versus {first['b']})",
                obligation_id,
            )
        return self._vote(
            VerdictDecision.PASS,
            f"the two model families agree on all {total} inputs",
            obligation_id,
        )

    def _vote(
        self, decision: VerdictDecision, reason: str, obligation_id: str | None
    ) -> OracleVote:
        return OracleVote(
            oracle_name=self.name,
            decision=decision,
            weight=self.weight,
            reason=reason,
            obligation_id=obligation_id,
        )

    async def _second_implementation(self, spec: SealedSpec) -> str:
        obligations = "\n".join(f"- {o.id}: {o.description}" for o in spec.obligations)
        prompt = (
            "Implement the specification below as a single Python module. Return "
            "ONLY Python source code: no prose, no markdown fences.\n\n"
            f"Title: {spec.title}\nObligations:\n{obligations}\n"
        )
        result = await self.llm.call(prompt, model=self.second_model)
        return extract_python_source(result.text)

    async def _comparison_inputs(self, spec: SealedSpec) -> list[str]:
        obligations = "\n".join(f"- {o.id}: {o.description}" for o in spec.obligations)
        prompt = (
            "A Python implementation of the specification below is defined. Write at "
            "least three concrete call expressions that exercise it, one per line, "
            "each a single expression that returns a value (for example "
            "`add(2, 3)`). Use only literal arguments. Output ONLY the expressions, "
            "no asserts, no markdown, no explanation.\n\n"
            f"Title: {spec.title}\nObligations:\n{obligations}\n"
        )
        result = await self.llm.call(prompt, model=self.input_model)
        text = extract_python_source(result.text)
        return [line.strip() for line in text.splitlines() if line.strip() and "(" in line]

    async def self_test(self) -> ProbeResult:
        """Readiness probe: needs an LLM client and a docker daemon."""
        has_docker = shutil.which("docker") is not None
        return ProbeResult(
            status=ProbeStatus.GREEN if has_docker else ProbeStatus.AMBER,
            detail={
                "name": self.name,
                "second_model": self.second_model.value,
                "client": type(self.llm).__name__,
                "docker": has_docker,
            },
        )
