"""Report rendering — Markdown (human) + JSON (machine, for a driving coding agent)."""

from __future__ import annotations

import dataclasses
import json
from enum import Enum
from pathlib import Path
from typing import Any


def to_jsonable(obj: Any) -> Any:
    if isinstance(obj, Enum):
        return obj.value
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        return {k: to_jsonable(v) for k, v in dataclasses.asdict(obj).items()}
    if isinstance(obj, dict):
        return {k: to_jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple, set)):
        return [to_jsonable(v) for v in obj]
    return obj


def render_markdown(record: Any) -> str:
    r = record
    out: list[str] = []
    out.append("# Crucible report\n")
    out.append(f"**Target:** `{r.target}`  ·  **Access:** {r.profile.access}  "
               f"·  **Mode:** {r.mode}\n")
    ev = r.eval_result
    if ev:
        out.append("## Headline\n")
        out.append(f"- **Held-out catch rate (after fix): {ev.held_out_catch_rate:.0%}** "
                   f"(baseline vulnerable: {ev.baseline_held_out_catch_rate:.0%} of held-out "
                   f"attacks landed before the fix)")
        out.append(f"- Seen catch rate: {ev.seen_catch_rate:.0%}  ·  "
                   f"Generalization gap: {ev.generalization_gap:+.0%}  ·  "
                   f"Utility delta: {ev.utility_delta:+.0%}")
        out.append(f"- Sets: seen={ev.n_seen}, held-out={ev.n_held_out}, benign={ev.n_benign}\n")
    if getattr(r, "audit", None):
        a = r.audit
        out.append(f"- **Fix durability (fix-aware re-attack): "
                   f"{'DURABLE ✓' if a['durable'] else 'BYPASSABLE ✗'}** "
                   f"({a['n_leaks']}/{a['n_attacks']} transform-based attacks leaked)\n")
    out.append("## Findings\n")
    if not r.findings:
        out.append("_No confirmed vulnerabilities._\n")
    for f in r.findings:
        out.append(f"- **[{f.severity.value.upper()}] {f.attack.attack_class.value}** "
                   f"via `{f.attack.technique}` @ `{f.surface}`")
        out.append(f"  - proof: {f.proof.detail} "
                   f"({'ground-truth' if f.proof.deterministic else 'judge'})")
        out.append(f"  - payload: `{f.attack.payload[:90]}`")
    out.append("\n## Vulnerabilities & fixes\n")
    fixes_by_v = {c.vulnerability_id: c for c in r.fixes}
    for v in r.vulnerabilities:
        out.append(f"### {v.id} — {v.attack_class.value} @ {v.surface} "
                   f"({v.severity.value})")
        out.append(f"- root cause: {v.root_cause}")
        c = fixes_by_v.get(v.id)
        if c:
            status = "✅ applied" if c.accepted else "⚠️ suggestion only"
            out.append(f"- fix [{c.layer}] — {status}: {c.description}")
            if c.notes:
                out.append(f"  - note: {c.notes}")
            out.append("```diff")
            out.append(c.diff.rstrip())
            out.append("```")
    if ev and ev.per_class:
        out.append("\n## Per-class held-out catch rate\n")
        for cls, m in ev.per_class.items():
            out.append(f"- {cls}: {m['catch_rate']:.0%} "
                       f"({int(m['still_succeeding'])}/{int(m['held_out_attacks'])} still land)")
        if ev.residual:
            out.append(f"\n**Residual** ({len(ev.residual)} held-out attacks still get through):")
            for p in ev.residual[:10]:
                out.append(f"- `{p[:90]}`")
    out.append("\n---\n_Generated by Crucible. Fixes are diffs, never applied live._")
    return "\n".join(out) + "\n"


def write_report(out_dir: str, record: Any) -> tuple[str, str]:
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    md_path = str(Path(out_dir) / "report.md")
    json_path = str(Path(out_dir) / "report.json")
    Path(md_path).write_text(render_markdown(record), encoding="utf-8")
    payload = {
        "target": record.target,
        "mode": record.mode,
        "profile": to_jsonable(record.profile),
        "findings": to_jsonable(record.findings),
        "vulnerabilities": to_jsonable(record.vulnerabilities),
        "fixes": to_jsonable(record.fixes),
        "eval": to_jsonable(record.eval_result),
        "fix_durability": to_jsonable(record.audit),
        "config_patch": to_jsonable(record.patch),
        "narration": record.narration,
    }
    Path(json_path).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return md_path, json_path
