// Crucible demo recorder. Config-driven Playwright capture of one US-n scenario.
// Records a webm of the live page walk, dumps the backing API payload(s) for the
// integrity reviewer, and writes the rendered innerText + a final screenshot.
//
// Usage: node demo/recorder.mjs <scenario.json>
// scenario.json: { id, title, base, page, waitText, dwellMs, apiRoutes:[...],
//                  steps:[ {action:"scroll"|"click"|"wait", ...} ] }
//
// Playwright is resolved from the global npx cache (no project install).
import fs from 'node:fs';
const { chromium } = await import(process.env.PW_PATH);

const cfgPath = process.argv[2];
const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
const outDir = `demo/clips`;
fs.mkdirSync(outDir, { recursive: true });
fs.mkdirSync('demo/integrity', { recursive: true });

const VW = 1366, VH = 854;

function log(...a) { console.log(`[rec ${cfg.id}]`, ...a); }

const browser = await chromium.launch({ args: ['--no-sandbox'] });
const context = await browser.newContext({
  viewport: { width: VW, height: VH },
  recordVideo: { dir: outDir, size: { width: VW, height: VH } },
  deviceScaleFactor: 2,
});
const page = await context.newPage();

const consoleErrs = [];
page.on('console', m => { if (m.type() === 'error') consoleErrs.push(m.text()); });
const failed = [];
page.on('requestfailed', r => failed.push(r.url()));

const url = `${cfg.base}${cfg.page}`;
log('navigate', url);
await page.goto(url, { waitUntil: 'networkidle', timeout: 60000 });

if (cfg.waitText) {
  log('wait for text:', cfg.waitText);
  await page.getByText(cfg.waitText, { exact: false }).first()
    .waitFor({ timeout: 30000 }).catch(() => log('WARN waitText not found'));
}
await page.waitForTimeout(1200);

for (const step of (cfg.steps || [])) {
  if (step.action === 'scroll') {
    await page.mouse.wheel(0, step.dy || 400);
    await page.waitForTimeout(step.ms || 900);
  } else if (step.action === 'click') {
    const el = page.locator(step.selector).first();
    await el.scrollIntoViewIfNeeded().catch(() => {});
    await el.click({ timeout: 8000 }).catch(e => log('click miss', step.selector, e.message));
    await page.waitForTimeout(step.ms || 1500);
  } else if (step.action === 'clickText') {
    const el = page.getByText(step.text, { exact: !!step.exact }).first();
    await el.scrollIntoViewIfNeeded().catch(() => {});
    await el.click({ timeout: 8000 }).catch(e => log('clickText miss', step.text, e.message));
    await page.waitForTimeout(step.ms || 1500);
  } else if (step.action === 'wait') {
    await page.waitForTimeout(step.ms || 1000);
  } else if (step.action === 'scrollTop') {
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'smooth' }));
    await page.waitForTimeout(step.ms || 800);
  }
}

await page.waitForTimeout(cfg.dwellMs || 1500);

// Capture final state evidence.
const innerText = await page.evaluate(() => document.body.innerText);
fs.writeFileSync(`demo/integrity/${cfg.id}.rendered.txt`, innerText);
await page.screenshot({ path: `demo/integrity/${cfg.id}.final.png`, fullPage: true });

// Pull backing API payloads for the integrity reviewer.
const payloads = {};
for (const route of (cfg.apiRoutes || [])) {
  try {
    const res = await page.request.get(`${cfg.base}${route}`, { timeout: 20000 });
    const ct = res.headers()['content-type'] || '';
    payloads[route] = ct.includes('json') ? await res.json() : (await res.text()).slice(0, 20000);
  } catch (e) { payloads[route] = { __error: e.message }; }
}
fs.writeFileSync(`demo/integrity/${cfg.id}.api.json`, JSON.stringify(payloads, null, 2));

await context.close();   // finalizes the video
await browser.close();

// Rename the autogenerated video to a stable name.
const vids = fs.readdirSync(outDir).filter(f => f.endsWith('.webm'));
vids.sort((a, b) => fs.statSync(`${outDir}/${b}`).mtimeMs - fs.statSync(`${outDir}/${a}`).mtimeMs);
if (vids[0]) {
  const dest = `${outDir}/${cfg.id}.webm`;
  fs.renameSync(`${outDir}/${vids[0]}`, dest);
  log('video ->', dest);
}
fs.writeFileSync(`demo/integrity/${cfg.id}.health.json`, JSON.stringify({ consoleErrs, failed }, null, 2));
log('consoleErrs', consoleErrs.length, 'failedReq', failed.length);
log('done');
await browser.close().catch(() => {});
